services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Basilicom\PimcorePluginMigrationToolkit\Command\:
        resource: '../../Command'
        public: true

    Basilicom\PimcorePluginMigrationToolkit\Translation\TranslationImporter: ~
    Basilicom\PimcorePluginMigrationToolkit\Translation\Reader\CsvTranslationReader: ~
    Basilicom\PimcorePluginMigrationToolkit\Translation\Reader\YamlCatalogueReader: ~
